mod browser;
mod library;
mod playlist;
mod settings;

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

use crate::app::App;
use crate::constants::runtime;
use crate::event::AppEvent;
use crate::ui::views::playlist_view::{InsertMode, LineTarget, PlaylistFlatModel};
use crate::ui::{RepeatMode, ViewMode};

impl App {
    pub(super) fn handle_event(&mut self, event: AppEvent) {
        match event {
            AppEvent::Quit => {
                self.save_state();
                self.should_quit = true;
            }
            AppEvent::JumpTop => {
                self.ui_state.selected_index = 0;
                self.ui_state.scroll_offset = 0;
            }
            AppEvent::RemoveSelected => self.handle_remove_selected(),
            AppEvent::Key(key) => self.handle_key_event(key),
            AppEvent::Tick => self.handle_tick(),
        }
    }

    // ── Keybinding helpers ──

    /// Check if a key event matches a configured keybinding string
    fn key_matches(&self, key: &KeyEvent, binding: &str) -> bool {
        let expected = crate::input::keymap::parse_key_str(binding);
        key.code == expected.code && key.modifiers == expected.modifiers
    }

    // ── Key event dispatch ──

    fn handle_key_event(&mut self, key: KeyEvent) {
        // Library search mode: ALL keys (including numbers, q, etc.) go to search input
        if self.ui_state.library_state.search_mode {
            self.handle_library_key(&key);
            return;
        }

        // Insert mode: all keys pass through to playlist handler
        if matches!(
            self.ui_state.playlist_state.insert_mode,
            InsertMode::Typing(_)
        ) {
            self.handle_playlist_key(&key);
            return;
        }

        // Command mode: all keys go to command input
        if self.ui_state.command_mode {
            self.handle_command_input(key);
            return;
        }

        // Help overlay: j/k scroll, 0/Esc to close
        if self.ui_state.show_help {
            match key.code {
                KeyCode::Char('j') | KeyCode::Down => {
                    self.ui_state.help_scroll += 1;
                }
                KeyCode::Char('k') | KeyCode::Up => {
                    self.ui_state.help_scroll = self.ui_state.help_scroll.saturating_sub(1);
                }
                KeyCode::Char('0') | KeyCode::Esc => {
                    self.ui_state.show_help = false;
                    self.ui_state.help_scroll = 0;
                }
                _ => {}
            }
            return;
        }

        // View switching (works in all views)
        match key.code {
            KeyCode::Char('1') => self.switch_view(ViewMode::Player),
            KeyCode::Char('2') => self.switch_view(ViewMode::Library),
            KeyCode::Char('3') => self.switch_view(ViewMode::Lyrics),
            KeyCode::Char('4') => self.switch_view(ViewMode::Visualizer),
            KeyCode::Char('5') => self.switch_view(ViewMode::Playlists),
            KeyCode::Char('6') => self.switch_view(ViewMode::Browser),
            KeyCode::Char('7') => self.switch_view(ViewMode::Settings),
            KeyCode::Char('0') => {
                // Cooldown guard: ignore spurious '0' events generated by
                // terminal escape-sequence interference (SIXEL/Kitty output).
                // Debounce window: 500ms.
                let now = std::time::Instant::now();
                let blocked = self
                    .ui_state
                    .last_help_toggle
                    .is_some_and(|t| now.duration_since(t).as_millis() < 500);
                if !blocked {
                    self.ui_state.show_help = !self.ui_state.show_help;
                    self.ui_state.last_help_toggle = Some(now);
                }
            }
            KeyCode::Esc => {
                if self.ui_state.show_help {
                    self.ui_state.show_help = false;
                } else {
                    self.search_mode = false;
                    self.ui_state.search_query.clear();
                }
            }
            _ => {
                // View-specific interception
                match self.ui_state.active_view {
                    ViewMode::Playlists => {
                        self.handle_playlist_key(&key);
                        return;
                    }
                    ViewMode::Browser => {
                        self.handle_file_browser_key(&key);
                        return;
                    }
                    ViewMode::Library => {
                        self.handle_library_key(&key);
                        return;
                    }
                    ViewMode::Settings => {
                        self.handle_settings_key(&key);
                        return;
                    }
                    _ => {}
                }
            }
        }

        // Player View: sidebar playlist navigation
        if self.ui_state.active_view == ViewMode::Player
            && self.handle_player_view_sidebar_key(&key)
        {
            return;
        }

        // Global key bindings
        self.handle_global_key(key);
    }

    /// Returns true if the key was consumed by the sidebar.
    fn handle_player_view_sidebar_key(&mut self, key: &KeyEvent) -> bool {
        let down = key.code == KeyCode::Down || self.key_matches(key, &self.key_bindings.down);
        let up = key.code == KeyCode::Up || self.key_matches(key, &self.key_bindings.up);

        if down {
            let ps = &mut self.ui_state.playlist_state;
            let model = PlaylistFlatModel::new(&ps.playlists, ps.expanded_playlist);
            // Max reachable index = last item (total - 1, since "..." at 0)
            let max_idx = model.total_lines().saturating_sub(1);
            if ps.selected_playlist < max_idx {
                ps.selected_playlist += 1;
            }
            // Mini playlist occupies bottom half of left panel
            let vis = self.ui_state.visible_rows.get() / 2;
            Self::clamp_playlist_scroll(ps, vis);
            return true;
        }
        if up {
            let ps = &mut self.ui_state.playlist_state;
            // Index 0 is the "..." row in the model — not selectable.
            // The first playlist starts at index 1.
            if ps.selected_playlist > 1 {
                ps.selected_playlist -= 1;
            }
            if ps.selected_playlist < ps.scroll_playlists {
                ps.scroll_playlists = ps.selected_playlist;
            }
            return true;
        }
        match key.code {
            KeyCode::Enter => {
                let ps = &self.ui_state.playlist_state;
                let model = PlaylistFlatModel::new(&ps.playlists, ps.expanded_playlist);
                match model.resolve(ps.selected_playlist) {
                    LineTarget::Song {
                        playlist,
                        song_index,
                    } => {
                        let pl_idx = ps.expanded_playlist.unwrap_or(playlist);
                        if pl_idx < ps.playlists.len()
                            && song_index < ps.playlists[pl_idx].songs.len()
                        {
                            let path = ps.playlists[pl_idx].songs[song_index].clone();
                            // Set this as the active playlist for scoped playback
                            self.ui_state.active_playlist = Some(pl_idx);
                            self.ui_state.active_playlist_song = Some(song_index);
                            // Update playlist_name for display
                            self.ui_state.playlist_name = ps.playlists[pl_idx].name.clone();
                            let _ = ps;
                            let _ = model;
                            self.load_and_play(&path);
                            return true;
                        }
                    }
                    LineTarget::PlaylistName(i) => {
                        let _ = model;
                        let ps = &mut self.ui_state.playlist_state;
                        // Toggle expand
                        if ps.expanded_playlist == Some(i) {
                            ps.expanded_playlist = None;
                        } else {
                            ps.expanded_playlist = Some(i);
                            // Set as active playlist on expand
                            self.ui_state.active_playlist = Some(i);
                            self.ui_state.playlist_name = ps.playlists[i].name.clone();
                        }
                        let new_model = PlaylistFlatModel::new(&ps.playlists, ps.expanded_playlist);
                        if let Some(new_line) = new_model.line_of_playlist(i) {
                            ps.selected_playlist = new_line;
                        }
                        Self::clamp_playlist_scroll(ps, self.ui_state.visible_rows.get() / 2);
                    }
                    _ => {}
                }
                true
            }
            _ => false,
        }
    }

    fn handle_global_key(&mut self, key: KeyEvent) {
        let visible_h = 10u16;

        // `:` enters command mode (like Vim)
        if key.code == KeyCode::Char(':') && key.modifiers.is_empty() {
            if !self.search_mode {
                self.ui_state.command_mode = true;
                self.ui_state.command_buffer.clear();
            }
            return;
        }

        let is_play_pause = self.key_matches(&key, &self.key_bindings.play_pause);
        let is_vol_down = self.key_matches(&key, &self.key_bindings.vol_down);
        let is_vol_up = self.key_matches(&key, &self.key_bindings.vol_up);
        let is_next = self.key_matches(&key, &self.key_bindings.next_track);
        let is_prev = self.key_matches(&key, &self.key_bindings.prev_track);
        let is_down = key.code == KeyCode::Down || self.key_matches(&key, &self.key_bindings.down);
        let is_up = key.code == KeyCode::Up || self.key_matches(&key, &self.key_bindings.up);

        if is_play_pause {
            if self.engine.is_playing() || self.ui_state.is_playing {
                self.engine.pause();
                self.ui_state.is_playing = false;
            } else {
                self.engine.resume();
                self.ui_state.is_playing = true;
            }
        } else if is_vol_down {
            let new_vol = (self.ui_state.volume - runtime::VOLUME_STEP).max(0.0);
            self.ui_state.volume = new_vol;
            self.engine.set_volume(new_vol);
        } else if is_vol_up {
            let new_vol = (self.ui_state.volume + runtime::VOLUME_STEP).min(1.0);
            self.ui_state.volume = new_vol;
            self.engine.set_volume(new_vol);
        } else if is_next {
            self.next_track();
        } else if is_prev {
            self.prev_track();
        } else if is_down {
            self.move_selection(1, visible_h);
        } else if is_up {
            self.move_selection(-1, visible_h);
        } else {
            match key.code {
                // Seeking
                KeyCode::Left => {
                    if let Err(e) = self
                        .engine
                        .seek_relative(-(self.config.playback.seek_step_small_secs as f64))
                    {
                        tracing::error!("Seek error: {e}");
                    }
                }
                KeyCode::Right => {
                    if let Err(e) = self
                        .engine
                        .seek_relative(self.config.playback.seek_step_small_secs as f64)
                    {
                        tracing::error!("Seek error: {e}");
                    }
                }
                // Navigation
                KeyCode::Char('G') => {
                    let len = self.ui_state.tracks.len();
                    if len > 0 {
                        self.ui_state.selected_index = len.saturating_sub(1);
                    }
                }
                KeyCode::Char('u') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                    let half = (visible_h / 2).max(1) as i32;
                    self.move_selection(-half, visible_h);
                    self.move_scroll(-half);
                }
                KeyCode::Char('d') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                    let half = (visible_h / 2).max(1) as i32;
                    self.move_selection(half, visible_h);
                    self.move_scroll(half);
                }
                // Modes
                KeyCode::Char('r') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                    self.ui_state.lyrics_offset_ms = 0;
                }
                KeyCode::Char('r') => {
                    self.ui_state.repeat_mode = match self.ui_state.repeat_mode {
                        RepeatMode::Sequential => RepeatMode::Shuffle,
                        RepeatMode::Shuffle => RepeatMode::SingleTrack,
                        RepeatMode::SingleTrack => RepeatMode::Sequential,
                    };
                    let label = self.ui_state.repeat_mode.label().to_string();
                    self.ui_state.notification = Some((label, std::time::Instant::now()));
                }
                KeyCode::Enter => self.play_selected(),
                // Lyrics offset
                KeyCode::Char('[') => self.ui_state.lyrics_offset_ms -= 500,
                KeyCode::Char(']') => self.ui_state.lyrics_offset_ms += 500,
                KeyCode::Char('{') => self.ui_state.lyrics_offset_ms -= 2000,
                KeyCode::Char('}') => self.ui_state.lyrics_offset_ms += 2000,
                // Search
                KeyCode::Char('/') => {
                    self.search_mode = true;
                    self.ui_state.search_query.clear();
                }
                _ => {
                    if self.search_mode {
                        self.handle_search_input(key);
                    }
                }
            }
        }
    }

    fn handle_search_input(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Char(c) if c != '/' => self.ui_state.search_query.push(c),
            KeyCode::Backspace => {
                self.ui_state.search_query.pop();
            }
            KeyCode::Esc => {
                self.search_mode = false;
                self.ui_state.search_query.clear();
            }
            _ => {}
        }
    }

    // ── Command mode ──

    fn handle_command_input(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Enter => {
                let cmd = crate::input::command::parse_command(&self.ui_state.command_buffer);
                self.dispatch_command(cmd);
                self.ui_state.command_mode = false;
                self.ui_state.command_buffer.clear();
            }
            KeyCode::Esc => {
                self.ui_state.command_mode = false;
                self.ui_state.command_buffer.clear();
            }
            KeyCode::Backspace => {
                self.ui_state.command_buffer.pop();
            }
            KeyCode::Char(c) => {
                self.ui_state.command_buffer.push(c);
            }
            _ => {}
        }
    }

    fn dispatch_command(&mut self, cmd: crate::input::command::Command) {
        match cmd {
            crate::input::command::Command::Quit => {
                self.save_state();
                self.should_quit = true;
            }
            crate::input::command::Command::Help => {
                self.ui_state.show_help = true;
            }
            crate::input::command::Command::Version => {
                self.ui_state.notification =
                    Some(("tmper v0.1.0".to_string(), std::time::Instant::now()));
            }
            crate::input::command::Command::Theme(name) => {
                self.config.ui.theme = name;
                Self::write_config(&self.config);
            }
            crate::input::command::Command::Seek(arg) => {
                if let Ok(secs) = arg.parse::<f64>() {
                    let _ = self.engine.seek_relative(secs);
                }
            }
            crate::input::command::Command::Volume(v) => {
                let vol = (v as f32) / 100.0;
                self.ui_state.volume = vol;
                self.engine.set_volume(vol);
            }
            crate::input::command::Command::Repeat(arg) => {
                let new_mode = match arg.to_lowercase().as_str() {
                    "shuffle" | "random" => crate::ui::RepeatMode::Shuffle,
                    "single" | "one" => crate::ui::RepeatMode::SingleTrack,
                    _ => crate::ui::RepeatMode::Sequential,
                };
                self.ui_state.repeat_mode = new_mode;
            }
            crate::input::command::Command::Shuffle(arg) => {
                self.ui_state.repeat_mode = match arg.to_lowercase().as_str() {
                    "on" | "true" | "yes" => crate::ui::RepeatMode::Shuffle,
                    _ => crate::ui::RepeatMode::Sequential,
                };
            }
            crate::input::command::Command::View(name) => {
                let view = match name.to_lowercase().as_str() {
                    "player" | "1" => crate::ui::ViewMode::Player,
                    "library" | "2" => crate::ui::ViewMode::Library,
                    "lyrics" | "3" => crate::ui::ViewMode::Lyrics,
                    "visualizer" | "4" => crate::ui::ViewMode::Visualizer,
                    "playlists" | "5" => crate::ui::ViewMode::Playlists,
                    "browser" | "6" => crate::ui::ViewMode::Browser,
                    "settings" | "7" => crate::ui::ViewMode::Settings,
                    _ => {
                        self.ui_state.notification =
                            Some((format!("Unknown view: {name}"), std::time::Instant::now()));
                        return;
                    }
                };
                if view == crate::ui::ViewMode::Library {
                    self.ensure_library_loaded();
                }
                self.ui_state.active_view = view;
            }
            crate::input::command::Command::Import(path) => {
                let import_path = std::path::PathBuf::from(&path);
                match crate::library::playlist_manager::import_m3u(&import_path) {
                    Ok(playlist) => {
                        let songs: Vec<std::path::PathBuf> =
                            playlist.tracks.iter().map(|t| t.path.clone()).collect();
                        let name = playlist.name.clone();
                        let count = playlist.tracks.len();
                        self.ui_state
                            .playlist_state
                            .playlists
                            .push(crate::ui::views::playlist_view::PlaylistData { name, songs });
                        self.save_playlists();
                        self.ui_state.notification = Some((
                            format!("Imported: {count} tracks"),
                            std::time::Instant::now(),
                        ));
                    }
                    Err(e) => {
                        self.ui_state.notification =
                            Some((format!("Import failed: {e}"), std::time::Instant::now()));
                    }
                }
            }
            crate::input::command::Command::Export(name) => {
                let ps = &self.ui_state.playlist_state;
                if let Some((_, pl_data)) = ps
                    .playlists
                    .iter()
                    .enumerate()
                    .find(|(_, p)| p.name.to_lowercase() == name.to_lowercase())
                {
                    let mut playlist = crate::playlist::Playlist::new(&pl_data.name);
                    for song in &pl_data.songs {
                        let title = song
                            .file_stem()
                            .and_then(|s| s.to_str())
                            .unwrap_or("Unknown")
                            .to_string();
                        playlist.push(crate::playlist::TrackEntry::new(
                            song.clone(),
                            title,
                            String::new(),
                            0.0,
                        ));
                    }
                    let export_path =
                        crate::paths::data_dir().join(format!("{}.m3u", pl_data.name));
                    match crate::library::playlist_manager::export_m3u(&playlist, &export_path) {
                        Ok(()) => {
                            self.ui_state.notification = Some((
                                format!("Exported to {}", export_path.display()),
                                std::time::Instant::now(),
                            ));
                        }
                        Err(e) => {
                            self.ui_state.notification =
                                Some((format!("Export failed: {e}"), std::time::Instant::now()));
                        }
                    }
                } else {
                    self.ui_state.notification = Some((
                        format!("Playlist not found: {name}"),
                        std::time::Instant::now(),
                    ));
                }
            }
            crate::input::command::Command::Unknown(cmd) => {
                self.ui_state.notification =
                    Some((format!("Unknown command: {cmd}"), std::time::Instant::now()));
            }
        }
    }

    fn handle_remove_selected(&mut self) {
        if self.ui_state.active_view == ViewMode::Playlists {
            let state = &mut self.ui_state.playlist_state;
            if state.selected_playlist > 0 {
                let model = PlaylistFlatModel::new(&state.playlists, state.expanded_playlist);
                if let LineTarget::PlaylistName(i) = model.resolve(state.selected_playlist) {
                    state.playlists.remove(i);
                    state.selected_playlist = state.selected_playlist.min(state.playlists.len());
                    state.expanded_playlist = None;
                    self.save_playlists();
                }
            }
            return;
        }
        let idx = self.ui_state.selected_index;
        if idx < self.ui_state.tracks.len() {
            if self.ui_state.playing_index == Some(idx) {
                self.ui_state.is_playing = false;
                self.engine.stop();
                self.ui_state.playing_index = None;
                self.ui_state.lyric_track = None;
            }
            self.ui_state.tracks.remove(idx);
            if self.ui_state.selected_index >= self.ui_state.tracks.len() {
                self.ui_state.selected_index = self.ui_state.tracks.len().saturating_sub(1);
            }
            if let Some(pi) = self.ui_state.playing_index {
                if pi > idx {
                    self.ui_state.playing_index = Some(pi - 1);
                }
            }
        }
    }

    fn handle_tick(&mut self) {
        // Notification auto-dismiss
        if let Some((_, time)) = &self.ui_state.playlist_state.notification {
            if time.elapsed().as_secs_f64() >= runtime::PLAYLIST_NOTIFICATION_SECS {
                self.ui_state.playlist_state.notification = None;
            }
        }
        // Mode change notification auto-dismiss (0.5s)
        if let Some((_, time)) = &self.ui_state.notification {
            if time.elapsed().as_secs_f64() >= runtime::NOTIFICATION_DURATION_SECS {
                self.ui_state.notification = None;
            }
        }

        let pos = self.engine.position_secs();
        self.ui_state.position = pos;

        if let Some(dur) = self.engine.duration_secs() {
            self.ui_state.duration = dur;
        }

        // Read FFT data
        if let Ok(data) = self.fft_data.lock() {
            if !data.is_empty() {
                self.ui_state.visualizer_data = data.clone();
            } else if !self.ui_state.is_playing {
                let mut bars = self.ui_state.visualizer_data.clone();
                for v in bars.iter_mut() {
                    *v *= 0.9;
                    if *v < 0.01 {
                        *v = 0.0;
                    }
                }
                self.ui_state.visualizer_data = bars;
            }
        }

        self.sync_lyrics(pos);

        if self.ui_state.is_playing && self.ui_state.duration > 0.0 && pos >= self.ui_state.duration
        {
            self.on_track_ended();
        }

        // Sync config flag to UI state (user may have toggled in settings)
        self.ui_state.show_cover_art = self.config.ui.show_cover_art;
    }

    /// Switch to `target` view. If already on that view, toggle back to Player.
    /// Runs view-specific initialization before the switch.
    fn switch_view(&mut self, target: ViewMode) {
        // Always toggle back to Player if already on the target view
        if self.ui_state.active_view == target {
            self.ui_state.active_view = ViewMode::Player;
            return;
        }

        // Run view-specific setup before switching
        match target {
            ViewMode::Library => self.ensure_library_loaded(),
            ViewMode::Playlists => self.enter_playlist_view(),
            ViewMode::Browser => self.enter_file_browser(),
            ViewMode::Settings => {
                crate::ui::views::settings_view::rebuild_settings(
                    &mut self.ui_state.settings_state,
                    &self.config,
                    &self.key_bindings,
                );
            }
            _ => {}
        }

        self.ui_state.active_view = target;
    }

    // ── Helpers ──

    // ── Helpers moved to app/playback.rs: move_selection, move_scroll,
    //    play_selected, next_track, prev_track, on_track_ended,
    //    start_fft, load_lyrics_for_current, sync_lyrics ──
}
