# dracula theme for tmper
name = "dracula"
primary = "#8be9fd"
text = "#f8f8f2"
secondary = "#bd93f9"
muted = "#6272a4"
success = "#50fa7b"
warning = "#f1fa8c"
control = "#ff79c6"
accent = "#ffb86c"
album = "#8be9fd"
genre = "#50fa7b"
year = "#f1fa8c"
codec = "#6272a4"
bg = "#282a36"
