# nord theme for tmper
name = "nord"
primary = "#88c0d0"
text = "#eceff4"
secondary = "#d8dee9"
muted = "#4c566a"
success = "#a3be8c"
warning = "#ebcb8b"
control = "#b48ead"
accent = "#d08770"
album = "#88c0d0"
genre = "#a3be8c"
year = "#ebcb8b"
codec = "#4c566a"
bg = "#2e3440"
