# solarized-dark theme for tmper
name = "solarized-dark"
primary = "#2aa198"
text = "#839496"
secondary = "#93a1a1"
muted = "#586e75"
success = "#859900"
warning = "#b58900"
control = "#d33682"
accent = "#cb4b16"
album = "#268bd2"
genre = "#859900"
year = "#b58900"
codec = "#586e75"
bg = "#002b36"
